version: '3'

volumes:
  node_modules:
  build:
services:
  my-service-uat:
    build:
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - build:/app/build
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
        - ENV=PROD
